from aiogram import Bot, types

from Bot_Mykola.handlers.create_bot import *


'''CLIENT'''


@dp.message_handler(commands='start')
async def commands_start(message: types.Message):
    try:
        await bot.send_message(message.from_user.id, f'Hi {message.from_user.full_name}, i`m voice assistance Mykola')
        await message.delete()
    except:
        await message.reply('You can tolk with Mykola in private message, write to him: https://t.me/va_Mykola_bot')


@dp.message_handler(commands='help')
async def commands_start(message: types.Message):
    try:
        await bot.send_message(message.from_user.id, f'Hir instruction for use Mykola')
        await message.delete()
    except:
        await message.reply('You can tolk with Mykola in private message, write to him: https://t.me/va_Mykola_bot')


@dp.message_handler(commands=['function'])
async def commands_start(message: types.Message):
    try:
        await bot.send_message(message.from_user.id, 'List of function:\n-\n-\n-')
        await message.delete()
    except:
        await message.reply('You can tolk with Mykola in private message, write to him: https://t.me/va_Mykola_bot')


@dp.message_handler(commands=['developers'])
async def commands_start(message: types.Message):
    try:
        await bot.send_message(message.from_user.id, 'Mykola generated by I_NATION_I '
                                                     'and derix035 ')
        await message.delete()
    except:
        await message.reply('You can tolk with Mykola in private message, write to him: https://t.me/va_Mykola_bot')

